name: Build images

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      products: ${{ steps.query.outputs.products }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Query available board configs
        id: query
        run: |
          echo "products=$(jq -c '. | map(.product)' src/share/rsdk/configs/products.json)" >> $GITHUB_OUTPUT
  build-images:
    needs: [query]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        products: ${{ fromJSON(needs.query.outputs.products) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ${{ matrix.products }}
        uses: ./.github/actions/build
        with:
          product: ${{ matrix.products }}
          test-repo: true
          artifacts: true
